src/Entity/Avis.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert; //Pour le controlle de saisie

use App\Entity\Utilisateur;
use App\Entity\Produit;

use App\Repository\AvisRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AvisRepository::class)]
class Avis
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_avis = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Le champ obligatoire")]
    private ?int $nb_etoiles = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"champs obligatoire")]
    private ?string $commentaire = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_avis;

    #[ORM\Column]
    private ?int $signaler = 0;

    #[ORM\ManyToOne(inversedBy: 'avis')]
    #[ORM\JoinColumn(name: "id_client", referencedColumnName: "id_utilisateur")]
    private ?Utilisateur $id_client = null;

    #[ORM\ManyToOne(inversedBy: 'avis')]
    #[ORM\JoinColumn(name: "ref_produit", referencedColumnName: "ref")]
    private ?Produit $ref_produit = null;




    public function __construct()
    {
        $this->date_avis = new \DateTime(); // Valeur par défaut pour la date de l'avis
    }

    public function getId(): ?int
    {
        return $this->id_avis;
    }

    public function getNbEtoiles(): ?int
    {
        return $this->nb_etoiles;
    }

    public function setNbEtoiles(int $nb_etoiles): static
    {
        $this->nb_etoiles = $nb_etoiles;
        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): static
    {
        $this->commentaire = $commentaire;
        return $this;
    }

    public function getDateAvis(): ?\DateTimeInterface
    {
        return $this->date_avis;
    }

    public function setDateAvis(\DateTimeInterface $date_avis): static
    {
        $this->date_avis = $date_avis;
        return $this;
    }

    public function getSignaler(): ?int
    {
        return $this->signaler;
    }

    public function setSignaler(int $signaler): static
    {
        $this->signaler = $signaler;
        return $this;
    }

    public function getIdClient(): ?Utilisateur
    {
        return $this->id_client;
    }

    public function setIdClient(?Utilisateur $id_client): static
    {
        $this->id_client = $id_client;
        return $this;
    }

    public function getRefProduit(): ?Produit
    {
        return $this->ref_produit;
    }

    public function setRefProduit(?Produit $ref_produit): static
    {
        $this->ref_produit = $ref_produit;
        return $this;
    }
}

templates/qr_code_generator/index.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Qr Code</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container text-center">
    <h1>Détails de la Commande</h1>
    <p>Commande ID: {{ commande.id }}</p>
    <p>Date: {{ commande.dateCommande|date('Y-m-d') }}</p>
    <p>Total: {{ commande.totaleCommande }} TND</p>
     <p>Total: {{ commande.etat }} TND</p>

    <div class="mt-5">
        <h2>Produits Achetés</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Prix</th>
                    <th>Quantité</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for ligne in commande.getLignesCommande() %}
                    <tr>
                        <td>{{ ligne.produit.marque }}</td>
                        <td>{{ ligne.produit.prix }} TND</td>
                        <td>{{ ligne.quantite }}</td>
                        <td>{{ ligne.quantite * ligne.produit.prix }} TND</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row mt-5">
       <div class="row mt-5">
    <div class="col">
        <h2>QR Code</h2>
        <a href="{{ path('app_qr_code', {'id': commande.id}) }}"><img src="{{ qrCode }}" alt="QR Code de la commande"></a>
    </div>
</div>

    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>