src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
class Utilisateur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_utilisateur = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $genre = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $mot_de_passe = null;

    #[ORM\Column]
    private ?int $num_tel = null;

    #[ORM\Column(length: 255)]
    private ?string $role = null;

    #[ORM\Column(length: 255)]
    private ?string $matricule = null;

    #[ORM\Column(length: 255)]
    private ?string $attestation = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column]
    private ?int $tentative = null;

    #[ORM\Column]
    private ?float $taille = null;

    #[ORM\Column]
    private ?float $poids = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\ManyToOne(inversedBy: 'utilisateurs')]
    #[ORM\JoinColumn(name: "objectif", referencedColumnName: "id_obj")]
    private ?Objectif $objectif = null;

    #[ORM\OneToMany(mappedBy: 'id_client', targetEntity: Conseil::class)]
    private Collection $conseils;

    #[ORM\OneToMany(mappedBy: 'id_client', targetEntity: Reclamation::class)]
    private Collection $reclamations;

    #[ORM\OneToMany(mappedBy: 'id_client', targetEntity: Avis::class)]
    private Collection $avis;

    #[ORM\OneToMany(mappedBy: 'id_client', targetEntity: Commande::class)]
    private Collection $commandes;

    #[ORM\OneToMany(mappedBy: 'id_client', targetEntity: Panier::class)]
    private Collection $paniers;

    public function __construct()
    {
        $this->conseils = new ArrayCollection();
        $this->reclamations = new ArrayCollection();
        $this->avis = new ArrayCollection();
        $this->commandes = new ArrayCollection();
        $this->paniers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id_utilisateur;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getMotDePasse(): ?string
    {
        return $this->mot_de_passe;
    }

    public function setMotDePasse(string $mot_de_passe): static
    {
        $this->mot_de_passe = $mot_de_passe;

        return $this;
    }

    public function getNumTel(): ?int
    {
        return $this->num_tel;
    }

    public function setNumTel(int $num_tel): static
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule): static
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getAttestation(): ?string
    {
        return $this->attestation;
    }

    public function setAttestation(string $attestation): static
    {
        $this->attestation = $attestation;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTentative(): ?int
    {
        return $this->tentative;
    }

    public function setTentative(int $tentative): static
    {
        $this->tentative = $tentative;

        return $this;
    }

    public function getTaille(): ?float
    {
        return $this->taille;
    }

    public function setTaille(float $taille): static
    {
        $this->taille = $taille;

        return $this;
    }

    public function getPoids(): ?float
    {
        return $this->poids;
    }

    public function setPoids(float $poids): static
    {
        $this->poids = $poids;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getObjectif(): ?Objectif
    {
        return $this->objectif;
    }

    public function setObjectif(?Objectif $objectif): static
    {
        $this->objectif = $objectif;

        return $this;
    }

    /**
     * @return Collection<int, Conseil>
     */
    public function getConseils(): Collection
    {
        return $this->conseils;
    }

    public function addConseil(Conseil $conseil): static
    {
        if (!$this->conseils->contains($conseil)) {
            $this->conseils->add($conseil);
            $conseil->setIdClient($this);
        }

        return $this;
    }

    public function removeConseil(Conseil $conseil): static
    {
        if ($this->conseils->removeElement($conseil)) {
            // set the owning side to null (unless already changed)
            if ($conseil->getIdClient() === $this) {
                $conseil->setIdClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reclamation>
     */
    public function getReclamations(): Collection
    {
        return $this->reclamations;
    }

    public function addReclamation(Reclamation $reclamation): static
    {
        if (!$this->reclamations->contains($reclamation)) {
            $this->reclamations->add($reclamation);
            $reclamation->setIdClient($this);
        }

        return $this;
    }

    public function removeReclamation(Reclamation $reclamation): static
    {
        if ($this->reclamations->removeElement($reclamation)) {
            // set the owning side to null (unless already changed)
            if ($reclamation->getIdClient() === $this) {
                $reclamation->setIdClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): static
    {
        if (!$this->avis->contains($avi)) {
            $this->avis->add($avi);
            $avi->setIdClient($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): static
    {
        if ($this->avis->removeElement($avi)) {
            // set the owning side to null (unless already changed)
            if ($avi->getIdClient() === $this) {
                $avi->setIdClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

   

    
    
    /**
     * @return Collection<int, Panier>
     */
    public function getPaniers(): Collection
    {
        return $this->paniers;
    }

  

  
}

templates/back_user/ajouterConseiller.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Utilisateur
{% endblock %}


{% block body %}
	<style>
		.card-body h2.card-title {
			text-align: center;
			color: #56ab2f; /* Couleur du texte */
			font-size: 24px;
			font-family: "Roboto", sans-serif;
		}

		.custom-file-upload {
			border: 1px solid #ccc;
			display: inline-block;
			padding: 6px 12px;
			cursor: pointer;
			background-color: #f8f8f8;
			border-radius: 5px;
			margin-top: 10px;
		}
	</style>


	<div class="col-md-6 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">
				{% if emptySubmission %}
					<div class="alert alert-danger" role="alert">
						Veuillez remplir tous les champs convenablement.
					</div>
				{% endif %}
				<h2 class="card-title">Ajouter un conseiller</h2>
				<div class="forms-sample">
					{{ form_start(f,{'attr':{'novalidate':'novalidate'}}) }}
					<div class="form-group">
						<label for="exampleInputNom1">{{ form_label(f.nom) }}</label>
						{{ form_widget(f.nom, {'attr': {'class': 'form-control' ~ (form_errors(f.nom) ? ' is-invalid' : ''), 'id': 'exampleInputUsername1', 'placeholder': 'Nom'}}) }}
						{% if form_errors(f.nom) %}
							<div class="invalid-feedback">
								{{ form_errors(f.nom) }}
							</div>
						{% endif %}
					</div>
					<div class="form-group">
						<label for="exampleInputPrenom1">{{ form_label(f.prenom) }}</label>
						{{ form_widget(f.prenom, {'attr': {'class': 'form-control' ~ (form_errors(f.prenom) ? ' is-invalid' : ''), 'id': 'exampleInputEmail1', 'placeholder': 'Prenom'}}) }}
						{% if form_errors(f.prenom) %}
							<div class="invalid-feedback">
								{{ form_errors(f.prenom) }}
							</div>
						{% endif %}
					</div>
					<div class="form-group">
						<label for="exampleInputEmail1">{{ form_label(f.email) }}</label>
						{{ form_widget(f.email, {'attr': {'class': 'form-control' ~ (form_errors(f.email) ? ' is-invalid' : ''), 'id': 'exampleInputEmail1', 'placeholder': 'Email'}}) }}
						{% if form_errors(f.email) %}
							<div class="invalid-feedback">
								{{ form_errors(f.email) }}
							</div>
						{% endif %}
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">{{ form_label(f.motDePasse) }}</label>
						{{ form_widget(f.motDePasse, {'attr': {'class': 'form-control' ~ (form_errors(f.motDePasse) ? ' is-invalid' : ''), 'id': 'exampleInputPassword1', 'placeholder': 'Mot de passe'}}) }}
						{% if form_errors(f.motDePasse) %}
							<div class="invalid-feedback">
								{{ form_errors(f.motDePasse) }}
							</div>
						{% endif %}
					</div>
					<div class="form-group">
						<label for="exampleInputUsername1">{{ form_label(f.genre) }}</label>
						{{ form_widget(f.genre, {'attr': {'class': 'form-control' ~ (form_errors(f.genre) ? ' is-invalid' : ''), 'id': 'exampleInputUsername1', 'placeholder': 'Genre'}}) }}
						{% if form_errors(f.genre) %}
							<div class="invalid-feedback">
								{{ form_errors(f.genre) }}
							</div>
						{% endif %}
					</div>
					<div class="form-group">
						<label for="exampleInputUsername1">{{ form_label(f.numTel) }}</label>
						{{ form_widget(f.numTel, {'attr': {'class': 'form-control' ~ (form_errors(f.numTel) ? ' is-invalid' : ''), 'id': 'exampleInputUsername1', 'placeholder': 'Numéro de téléphone'}}) }}
						{% if form_errors(f.numTel) %}
							<div class="invalid-feedback">
								{{ form_errors(f.numTel) }}
							</div>
						{% endif %}
					</div>
					<div class="form-group">
						<label for="exampleInputMatricule1">{{ form_label(f.matricule) }}</label>
						{{ form_widget(f.matricule, {'attr': {'class': 'form-control' ~ (form_errors(f.matricule) ? ' is-invalid' : ''), 'id': 'exampleInputUsername1', 'placeholder': 'Matricule'}}) }}
						{% if form_errors(f.matricule) %}
							<div class="invalid-feedback">
								{{ form_errors(f.matricule) }}
							</div>
						{% endif %}
					</div>
					<div class="form-group">
						<label for="exampleInputUsername1">{{ form_label(f.attestation) }}</label>
						<div class="custom">
							{{ form_widget(f.attestation, {'attr': {'class': 'form-control' ~ (form_errors(f.attestation) ? ' is-invalid' : ''), 'id': 'exampleInputUsername1', 'placeholder': 'Attestation'}}) }}
						</div>
						{% if form_errors(f.attestation) %}
							<div class="invalid-feedback">
								{{ form_errors(f.attestation) }}
							</div>
						{% endif %}
					</div>
					<div class="form-group">
						<label for="exampleInputUsername1">{{ form_label(f.photo) }}</label>
						<div class="custom">
							{{ form_widget(f.photo, {'attr': {'class': 'form-control' ~ (form_errors(f.photo) ? ' is-invalid' : ''), 'id': 'exampleInputUsername1', 'placeholder': 'Photo'}}) }}
						</div>
						{% if form_errors(f.photo) %}
							<div class="invalid-feedback">
								{{ form_errors(f.photo) }}
							</div>
						{% endif %}
					</div>

					{{ form_end(f) }}
					<button class="btn btn-light" style="margin-left:130px; margin-top:-70px;" onclick="window.location.href='listUsers';">Cancel</button>
				</div>
			</div>
		</div>
	</div>


{% endblock %}

templates/back_user/clients_pdf.html.twig
{# templates/users/users_pdf.html.twig #}

<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>Liste des clients</title>
		<style>
			table {
				width: 100%;
				border-collapse: collapse;
			}
			th,
			td {
				border: 1px solid black;
				padding: 8px;
				text-align: left;
			}
			img {
				height: 50px;
			}
		</style>
	</head>
	<body>
		<h1 style="color:#56ab2f; text-align:center; font-style: italic;">
			Liste des clients
		</h1>
		<table>
			<thead style="color:white; background-color:#56ab2f;">
				<tr>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Genre</th>
					<th>Adresse</th>
					<th>Objectif</th>
					<th>Taille</th>
					<th>Poids</th>
				</tr>
			</thead>
			<tbody>
				{% for user in clients %}
					<tr>
						<td>{{ user.nom }}</td>
						<td>{{ user.prenom }}</td>
						<td>{{ user.genre }}</td>
						<td>{{ user.adresse }}</td>
						<td>
							{% if user.role == 'Client' %}
								{{ user.objectif.libelle }}
							{% endif %}
						</td>
						
						<td>{{ user.taille }}</td>
						<td>{{ user.poids }}</td>

					</tr>
				{% endfor %}
			</tbody>
		</table>
	</body>
</html>

templates/back_user/conseillers_pdf.html.twig
{# templates/users/users_pdf.html.twig #}

<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>Liste des clients</title>
		<style>
			table {
				width: 100%;
				border-collapse: collapse;
			}
			th,
			td {
				border: 1px solid black;
				padding: 8px;
				text-align: left;
			}
			img {
				height: 50px;
			}
		</style>
	</head>
	<body>
		<h1 style="color:#56ab2f; text-align:center; font-style: italic;">
			Liste des conseillers
		</h1>
		<table>
			<thead style="color:white; background-color:#56ab2f; margin-right:10px;">
				<tr>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Genre</th>
					<th>Email</th>
					<th>Numéro de téléphone</th>
					<th>Matricule</th>
				</tr>
			</thead>
			<tbody>
				{% for user in conseillers %}
					<tr>
						<td>{{ user.nom }}</td>
						<td>{{ user.prenom }}</td>
						<td>{{ user.genre }}</td>
						<td>{{ user.email }}</td>
						<td>{{ user.numTel }}</td>
						<td>{{ user.matricule }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</body>
</html>

templates/back_user/listUsers.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Utilisateur
{% endblock %}

{% block body %}

	<style>
		.table-striped tbody tr:hover {
			background-color: #bbddab; /* Couleur de fond au survol */
			color: #fff; /* Couleur du texte au survol */
		}

		.anchor-pane {
			display: flex;
			justify-content: space-around;
			margin-top: 20px;
		}

		.cards-container {
			display: flex;
			gap: 20px; /* Espacement entre les cartes */
			margin-left: -30px;
		}

		.card2 {
			background: linear-gradient(to right, #19330e, #56ab2f);
			border-radius: 5px;
			padding: 20px;
			color: white;
			text-align: center;
			width: 270px;
			position: relative;
			height: 200px;
		}

		.card2:hover {
			background: linear-gradient(to right, #56ab2f, #19330e);
		}

		.card-image {
			width: 86px;
			height: 78px;
			margin: 0 auto; /* Centrage horizontal de l'image */
			display: block; /* Assurer que l'image se comporte comme un bloc */
			position: absolute;
			top: 10px; /* Distance du haut */
			left: 10px;
		}

		.total {
			font-size: 30px;
			font-weight: bold;
			position: absolute;
			top: 10px; /* Distance du haut */
			right: 10px;
		}
		h3 {
			margin-top: 130px; /* Espacement entre l'image et le titre */

		}
		.table-striped tbody tr:nth-of-type(odd) {
			background-color: #ddeed5;
		}

		#successMessage {
			height: 50px;
			width: 250px;
			margin-right: 250px;
			position: absolute;
			z-index: 999;
		}

		#successMessageModif {
			height: 50px;
			width: 250px;
			margin-right: 250px;
			position: absolute;
			z-index: 999;
		}

		#icon {
			color: white;
		}

		#filtre {
			color: white;
		}
	</style>

	<div class="col-lg-10 grid-margin stretch-card">
		<div class="card">

			<div class="anchor-pane">
				<button type="button" class="btn btn-inverse-success btn-fw" style="margin-top:50px; width:300px; margin-left:30px; height:60px" onclick="window.location.href='ajouterConseiller';">Ajouter un conseiller</button>

				{% for flash_message in app.flashes('success') %}
					<div class="alert alert-success" id="successMessage" role="alert">
						{{ flash_message }}
					</div>
				{% endfor %}


				<div class="col-lg-2" style="margin-top:150px; margin-left:-370px">
					<form action="{{ path('usersList') }}" method="GET">
						<select name="role" class="form-control" onchange="this.form.submit()" style="background-color:#aad597" id="filtre">
							<option value="Tous">Tous</option>
							<option value="Client">Client</option>
							<option value="Conseiller">Conseiller</option>
						</select>
					</form>
				</div>

				<form method="get" action="{{ path('user_search') }}" style="margin-top:150px;">
					<div class="input-group mb-3" style="width:200px;">
						<input type="text" class="form-control" name="q" id="searchInput" placeholder="Rechercher" aria-label="Rechercher" aria-describedby="search" value="{{ searchQuery ?? '' }}">
						<div class="input-group-append hover-cursor" id="navbar-search-icon">
							<button class="btn btn-outline-secondary" type="submit" style="background-color:#aad597">
								<i class="icon-search" id="icon"></i>
							</button>
						</div>
					</div>
				</form>
				<a id="click_to_record"> <i class="icon-microphone menu-icon" style="margin-top:163px; margin-left:-20px;"></i> </a>
<script>
click_to_record.addEventListener('click',function(){
    var speech = true;
    window.SpeechRecognition = window.webkitSpeechRecognition;

    const recognition = new SpeechRecognition();
    recognition.interimResults = true;

    recognition.addEventListener('result', e => {
        const transcript = Array.from(e.results)
            .map(result => result[0])
            .map(result => result.transcript)
            .join('')

        document.getElementById("searchInput").value = transcript;
        console.log(transcript);
    });
    
    if (speech == true) {
        recognition.start();
    }
})
</script>
				<script>
					// Masquer l'alerte après 5 secondes
setTimeout(function () {
document.getElementById('successMessage').style.display = 'none';
}, 5000); // 5000 millisecondes = 5 secondes
				</script>

				{% for flash_message in app.flashes('success') %}
					<div class="alert alert-success" id="successMessageModif" role="alert">
						{{ flash_message }}
					</div>
				{% endfor %}

				<script>
					// Masquer l'alerte après 5 secondes
setTimeout(function () {
document.getElementById('successMessage').style.display = 'none';
}, 5000); // 5000 millisecondes = 5 secondes
				</script>

				<a href="{{ path('clients_pdf') }}" class="btn btn-inverse-success btn-fw" target="_blank" style="width:180px; height:50px; margin-top:80px; ">
					Exporter Clients en PDF
				</a>

				<a href="{{ path('conseillers_pdf') }}" class="btn btn-inverse-success btn-fw" target="_blank" style="width:180px; height:50px; margin-top:145px; margin-right:45px; margin-left:-200px;">
					Exporter Conseillers en PDF
				</a>

				<div class="cards-container">
					<div class="card2" id="cardClient">
						<img src="{{ asset('images/groupe.png') }}" alt="Total Clients" class="card-image">
						<h3>Total Clients</h3>
						<p id="totalClients" class="total">{{ totalClients }}</p>
					</div>
					<div class="card2" id="cardConseiller">
						<img src="{{ asset('images/nutritionniste_blanc.png') }}" alt="Total Conseillers" class="card-image">
						<h3>Total Conseillers</h3>
						<p id="totalConseillers" class="total">{{ totalConseillers }}</p>
					</div>
				</div>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<div class="table-wrapper">
						<table class="table table-striped">
							<thead style=" background-color: #77bb58; color: white; position: sticky; top: 0; z-index: 1;">
								<tr>
									<th>
										Photo
									</th>
									<th>
										Nom
									</th>
									<th>
										Prénom
									</th>
									<th>
										Genre
									</th>
									<th>
										Email
									</th>
									<th>
										Mot de passe
									</th>
									<th>
										Numéro tel
									</th>
									<th>
										Rôle
									</th>
									<th>
										Matricule
									</th>
									<th>
										Attestation
									</th>
									<th>
										Adresse
									</th>
									<th>
										Objectif
									</th>
									<th>
										Taille
									</th>
									<th>
										Poids
									</th>
									<th>
										Actions
									</th>
								</tr>
							</thead>
							<tbody>
								{% for user in users %}
									<tr>
										<td class="py-1">
											<img src="{{ asset('images/' ~ user.photo) }}" alt="Image">
										</td>
										<td>
											{{ user.nom }}
										</td>
										<td>
											{{ user.prenom }}
										</td>
										<td>
											{{ user.genre }}
										</td>
										<td>
											{{ user.email }}
										</td>
										<td>
											{{ user.motDePasse }}
										</td>
										<td>
											{{ user.numTel }}
										</td>
										<td>
											{{ user.role }}
										</td>
										<td>
											{{ user.matricule }}
										</td>
										<td>
											{{ user.attestation }}
										</td>
										<td>
											{{ user.adresse }}
										</td>
										<td>
											{% if user.role == 'Client' %}
												{{ user.objectif.libelle }}
											{% endif %}
										</td>
										<td>
											{{ user.taille }}
										</td>
										<td>
											{{ user.poids }}
										</td>
										<td>
											{% if user.role == 'Client' %}
												<button href="{{ path('conseiller_update', {'id': user.idUtilisateur}) }}" class="btn btn-warning btn-sm" disabled>
													<i class="ti-pencil menu-icon"></i>
												</button>
											{% endif %}
											{% if user.role == 'Conseiller' %}
												<a href="{{ path('conseiller_update', {'id': user.idUtilisateur}) }}" class="btn btn-warning btn-sm">
													<i class="ti-pencil menu-icon"></i>
												</a>
											{% endif %}

											{% if user.role == 'Client' %}
												<button class="btn btn-danger btn-sm" onclick="confirmSuppression('{{ path('conseiller_delete', {'id': user.idUtilisateur}) }}')" disabled>
													<i class="icon-trash menu-icon"></i>
												</button>
											{% endif %}
											{% if user.role == 'Conseiller' %}
												<a class="btn btn-danger btn-sm" onclick="confirmSuppression('{{ path('conseiller_delete', {'id': user.idUtilisateur}) }}')">
													<i class="icon-trash menu-icon"></i>
												</a>
											{% endif %}

										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					<div class="text-center mt-4">
						<div style="display: inline-block;">
							{{ knp_pagination_render(pagination, 'pagination.html.twig') }}
						</div>
					</div>
				</div>
			</div>


		</div>

	</div>

	<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script>
		function confirmSuppression(url) {
Swal.fire({
title: 'Êtes-vous sûr?',
text: "Vous êtes sur le point de supprimer cet article du panier!",
icon: 'warning',
showCancelButton: true,
confirmButtonColor: '#dc3545',
cancelButtonColor: '#28a745',
confirmButtonText: 'Oui, supprimer!'
}).then((result) => {
if (result.isConfirmed) {
window.location.href = url;
}
});
}
	</script>

	<script>
		// Fonction pour filtrer les résultats du tableau en fonction de la saisie de l'utilisateur
function filterTable() {
var input,
filter,
table,
tr,
td,
i,
txtValue;
input = document.getElementById("searchInput");
filter = input.value.toUpperCase();
table = document.getElementById("userTable");
tr = table.getElementsByTagName("tr");

for (i = 0; i < tr.length; i++) {
td = tr[i].getElementsByTagName("td")[1]; // Modifier l'index en fonction de la colonne que vous souhaitez rechercher
if (td) {
txtValue = td.textContent || td.innerText;
if (txtValue.toUpperCase().indexOf(filter) > -1) {
tr[i].style.display = "";
} else {
tr[i].style.display = "none";
}
}
}
}

// Ajoutez un écouteur d'événements pour déclencher la recherche à chaque fois que l'utilisateur tape quelque chose dans la barre de recherche
document.getElementById("searchInput").addEventListener("keyup", filterTable);
	</script>

{% endblock %}

templates/back_user/profilAdminMDP.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Utilisateur
{% endblock %}


{% block body %}
	<style>
		.card-body h2.card-title {
			text-align: center;
			color: #56ab2f; /* Couleur du texte */
			font-size: 24px;
			font-family: "Roboto", sans-serif;
		}

		.custom-file-upload {
			border: 1px solid #ccc;
			display: inline-block;
			padding: 6px 12px;
			cursor: pointer;
			background-color: #f8f8f8;
			border-radius: 5px;
			margin-top: 10px;
		}
	</style>


	<div class="col-md-6 grid-margin stretch-card" style="margin-left:100px;">
		<div class="card">
			<div class="card-body" style="margin-left:200px;">

				<h2 class="card-title" style="margin-top:100px;">Mot de passe</h2>
				<div class="forms-sample">
					{{ form_start(f,{'attr':{'novalidate':'novalidate'}}) }}
					<div class="form-group">
						<input type="password" name="ancienMDP" class="form-control form-control-lg" id="exampleInputEmail1" placeholder="Mot de passe actuel" required autofocus>
					</div>

					<div class="form-group">
						<label for="exampleInputPassword1">{{ form_label(f.motDePasse) }}</label>
						{{ form_widget(f.motDePasse, {'attr': {'class': 'form-control' ~ (form_errors(f.motDePasse) ? ' is-invalid' : ''), 'id': 'exampleInputPassword1', 'placeholder': 'Mot de passe'}}) }}
						{% if form_errors(f.motDePasse) %}
							<div class="invalid-feedback">
								{{ form_errors(f.motDePasse) }}
							</div>
						{% endif %}
					</div>
					{{ form_end(f) }}
				</div>
			</div>
		</div>
	</div>


{% endblock %}